name: Deploy to Remote Server

on:
  push:
    branches: [ main ]
    paths: [ 'public/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up SSH 🔑
      run: |
        mkdir -v -m 700 $HOME/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} > $HOME/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
        chmod 400 $HOME/.ssh/id_rsa
        
    - name: Upload public directory to server ⬆️
      run: |
        scp -r ./public/* ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:${{ secrets.REMOTE_PATH }}